# BookEditor Configuration file!
# @author syamn <admin@sakura-server.net>
# github: https://github.com/syamn/BookEditor

#==================#
#   Vault Config   #
#==================#
# Hook to Vault for economy integration
UseVault: false
# Costs
Cost:
  Copy: 100
  Edit: 100
  Title: 100

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
Version: 1.1